<a href="https://colab.research.google.com/github/cryptotitan22/Machine_Learning_Project/blob/main/Multiple_Linear_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!git clone https://github.com/cryptotitan22/Multiple_Linear_Regression.git

Cloning into 'Multiple_Linear_Regression'...


In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
df= pd.read_csv('Book 5.csv')
df

speed  car_age  experience  risk
0    200       15         5.0    85
1     90       17        13.0    20
2    165       12         4.0    93
3    110       20         NaN    60
4    140        5         3.0    82
5    115        2         8.0    10

In [ ]:
df.isnull().sum()

speed         0
car_age       0
experience    1
risk          0
dtype: int64

In [ ]:
mean = df.experience.mean()
mean

6.6

In [ ]:
df.experience = df.experience.fillna(mean)
df.experience

0     5.0
1    13.0
2     4.0
3     6.6
4     3.0
5     8.0
Name: experience, dtype: float64

In [ ]:
x = df[['speed','car_age','experience']].values
x

array([[200. ,  15. ,   5. ],
       [ 90. ,  17. ,  13. ],
       [165. ,  12. ,   4. ],
       [110. ,  20. ,   6.6],
       [140. ,   5. ,   3. ],
       [115. ,   2. ,   8. ]])

In [ ]:
y = df[['risk']].values
y

array([[85],
       [20],
       [93],
       [60],
       [82],
       [10]])

In [ ]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size =0.2,random_state=0)
xtrain

array([[ 90. ,  17. ,  13. ],
       [110. ,  20. ,   6.6],
       [200. ,  15. ,   5. ],
       [140. ,   5. ,   3. ]])

In [ ]:
xtest

array([[115.,   2.,   8.],
       [165.,  12.,   4.]])

In [ ]:
ytrain

array([[20],
       [60],
       [85],
       [82]])

In [ ]:
ytest

array([[10],
       [93]])

In [ ]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression()
reg.fit(xtrain,ytrain)

LinearRegression()

In [ ]:
reg.predict(xtest)

array([[48.77682403],
       [83.02813543]])

In [ ]:
reg.predict([[153,7,3]])

array([[85.00538865]])

In [ ]:
reg.coef_

array([[ 0.19318073,  0.24701955, -5.53051979]])

In [ ]:
reg.intercept_

array([70.3111588])

In [ ]:
70.3111588+((0.19318073*153 + 0.24701955*7)+(-5.53051979 *3))

85.00538797